name: Detectar errores

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: pip install requests

      - run: python scripts/reddit_scraper.py

      - run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "update" || echo "no changes"
          git push
